### ISSUE TITLE
Dex Contract Refine.

### ISSUE THREAD

**Issue by lychees** [Andoromeda-Foundation/dapp-examples#7]
- [x] Send asset in match function.
- [ ] Add Cancel function.
- [x] Onchain Match function.

Ref:
[Design Doc
](https://docs.google.com/document/d/15QaDuXQnBbLmyGUX2vnTnvwWlWDG_KsUazAiVAQrq4w/edit#)
Competitor:
https://newdex.io/
https://dexeos.io/

**Comment by yukiexe** [comment]
all be done.

**Comment by lychees** [comment]
Thanks.
